import { detectFrames } from "./animate";
import type {
  NonDeletedExcalidrawElement,
  ExcalidrawTextElement,
  ExcalidrawElement,
} from "@excalidraw/excalidraw/types/element/types";

describe("Frame Detection", () => {
  it("should detect frame elements", () => {
    const elements: NonDeletedExcalidrawElement[] = [
      {
        id: "frame1",
        type: "frame",
        x: 0,
        y: 0,
        width: 100,
        height: 100,
        angle: 0,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 0,
        opacity: 100,
        groupIds: [],
        frameId: null,
        roundness: null,
        seed: 1,
        version: 1,
        versionNonce: 1,
        isDeleted: false,
        boundElements: null,
        updated: 1,
        link: null,
        locked: false,
        customData: {},
        name: "Frame 1",
      } as any,
      {
        id: "text1",
        type: "text",
        x: 10,
        y: 10,
        width: 50,
        height: 20,
        angle: 0,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 0,
        opacity: 100,
        groupIds: [],
        frameId: null,
        roundness: null,
        seed: 1,
        version: 1,
        versionNonce: 1,
        isDeleted: false,
        boundElements: null,
        updated: 1,
        link: null,
        locked: false,
        text: "Hello",
        fontSize: 20,
        fontFamily: 1,
        textAlign: "left",
        verticalAlign: "top",
        baseline: 17,
        containerId: null,
        originalText: "Hello",
        lineHeight: Object.assign(1.25, { _brand: "unitlessLineHeight" }),
      } as ExcalidrawTextElement,
    ];

    expect(detectFrames(elements)).toBe(true);
  });

  it("should detect elements with frameId", () => {
    const elements: NonDeletedExcalidrawElement[] = [
      {
        id: "text1",
        type: "text",
        x: 10,
        y: 10,
        width: 50,
        height: 20,
        angle: 0,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 0,
        opacity: 100,
        groupIds: [],
        frameId: "frame1",
        roundness: null,
        seed: 1,
        version: 1,
        versionNonce: 1,
        isDeleted: false,
        boundElements: null,
        updated: 1,
        link: null,
        locked: false,
        text: "Hello",
        fontSize: 20,
        fontFamily: 1,
        textAlign: "left",
        verticalAlign: "top",
        baseline: 17,
        containerId: null,
        originalText: "Hello",
        lineHeight: Object.assign(1.25, { _brand: "unitlessLineHeight" }),
      } as ExcalidrawTextElement,
    ];

    expect(detectFrames(elements)).toBe(true);
  });

  it("should return false when no frames present", () => {
    const elements: NonDeletedExcalidrawElement[] = [
      {
        id: "text1",
        type: "text",
        x: 10,
        y: 10,
        width: 50,
        height: 20,
        angle: 0,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 0,
        opacity: 100,
        groupIds: [],
        frameId: null,
        roundness: null,
        seed: 1,
        version: 1,
        versionNonce: 1,
        isDeleted: false,
        boundElements: null,
        updated: 1,
        link: null,
        locked: false,
        text: "Hello",
        fontSize: 20,
        fontFamily: 1,
        textAlign: "left",
        verticalAlign: "top",
        baseline: 17,
        containerId: null,
        originalText: "Hello",
        lineHeight: Object.assign(1.25, { _brand: "unitlessLineHeight" }),
      } as ExcalidrawTextElement,
    ];

    expect(detectFrames(elements)).toBe(false);
  });

  it("should handle elements from example file", () => {
    const elements: NonDeletedExcalidrawElement[] = [
      {
        id: "LUYKaoc_kVxiQC1NVwfzw",
        type: "frame",
        x: 1449.9629573212255,
        y: 173.23293381585006,
        width: 1920,
        height: 1080,
        angle: 0,
        strokeColor: "#bbb",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        strokeStyle: "solid",
        roughness: 0,
        opacity: 100,
        groupIds: [],
        frameId: null,
        roundness: null,
        seed: 790614524,
        version: 46,
        versionNonce: 617736900,
        isDeleted: false,
        boundElements: null,
        updated: 1739117458809,
        link: null,
        locked: false,
        customData: {},
        name: "Frame 1",
      } as any,
    ];

    expect(detectFrames(elements)).toBe(true);
  });
});
